### ISSUE TITLE
<br /> tags visible in output

### ISSUE THREAD

**Issue by cmcaine** [CalculusWithJulia/CalculusWithJulia.github.io#14]
https://github.com/CalculusWithJulia/CalculusWithJulia.github.io/blob/661f318319a222ac53d5b972e1d4dea8ff90ac76/precalc/numbers_types.jmd#L349

These break tags are visible when they probably should not be. https://calculuswithjulia.github.io/precalc/numbers_types.html#Complexnumbers (scroll up slightly)

**Comment by jverzani** [comment]
Thanks!
