### ISSUE TITLE
Wrong quiz answer: 2^(-1) gives Float, not an error

### ISSUE THREAD

**Issue by cmcaine** [CalculusWithJulia/CalculusWithJulia.github.io#15]
https://github.com/CalculusWithJulia/CalculusWithJulia.github.io/blob/661f318319a222ac53d5b972e1d4dea8ff90ac76/precalc/numbers_types.jmd#L570

julia> 2^(-1)
0.5

**Comment by jverzani** [comment]
Thanks again!

**Comment by cmcaine** [comment]
You've fixed this slightly wrong :)

`ans` is an index into `choices` above. The correct index is 3.

**Comment by jverzani** [comment]
Yup! Thanks again!!
