### ISSUE TITLE
`return` is not a function

### ISSUE THREAD

**Issue by cmcaine** [CalculusWithJulia/CalculusWithJulia.github.io#16]
https://github.com/CalculusWithJulia/CalculusWithJulia.github.io/blob/661f318319a222ac53d5b972e1d4dea8ff90ac76/precalc/functions.jmd#L272

As I'm sure you know, return is not a function and doesn't need the brackets. You also mention a "return call".

By this point you've introduced other keywords (if, else, function, end), so one more shouldn't be too scary, right?

**Comment by jverzani** [comment]
Thanks again! I really appreciate your taking the time to point these issues out.

**Comment by cmcaine** [comment]
You're welcome! Thanks for writing the material!
