### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by chris2crawford** [CalculusWithJulia/CalculusWithJulia.github.io#19]
@jverzani

in http://calculuswithjulia.github.io/getting-started-with-julia.html  :
Bindar and Julia Box are great and convenient,  -> Binder

in  http://calculuswithjulia.github.io/julia_interfaces.html#  :
Notebooks can be saved (as *.ipynb files) for sharing or reused.  -> reuse
programming withing the language.  -> within

**Comment by jverzani** [comment]
Thanks Chris.  I'll add these changes.

**Comment by chris2crawford** [comment]
Thanks, John, for making this available.  It is very helpful for me, just
starting out with Julia.
--Chris

Christopher Crawford, Professor, Director of Graduate Studies
Department of Physics and Astronomy, University of Kentucky
859-257-2504 (o)  859-421-9612 (c)   skype: chris2crawford
schedule: www.pa.uky.edu/~crawford   uky.zoom.us/my/c.crawford

**Comment by jverzani** [comment]
Glad you find it useful! Any more feedback is most welcome.
