### ISSUE TITLE
Wrong answer for Sum of arithmetic progression

### ISSUE THREAD

**Issue by tomaklutfu** [CalculusWithJulia/CalculusWithJulia.github.io#2]
`h \cdot(a + n(n+1)/2)` is accepted as true but it seems the correct one is `(n+1)(a+h \cdot n/2)` so the answer should be `No, this is false`. Am I wrong?

**Comment by jverzani** [comment]
Oops, thanks for pointing this out. Yours is definitely a correct answer.

**Comment by jverzani** [comment]
fixed with last commit

**Comment by tomaklutfu** [comment]
Good. I just saw this today. I revise my knowledge with this. I did not ask earlier but is it ok if I report when I find more of this? or typos?

**Comment by jverzani** [comment]
Is it ok? It would be awesome and most appreciated.
