### ISSUE TITLE
Typo on odes

### ISSUE THREAD

**Issue by zwk24** [CalculusWithJulia/CalculusWithJulia.github.io#7]
should fix into 
$$~
\sqrt{h(t)} = \sqrt{h_0} -\frac{1}{2}\frac{a}{A}\sqrt{2g} t.
~$$
https://github.com/CalculusWithJulia/CalculusWithJulia.github.io/blob/master/ODEs/odes.mmd#L225

**Comment by jverzani** [comment]
Thanks!
